# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca40e257c34409e4b07f2f69a7ebcb4b03b64fb780246015d638db5d2926d6f5d6ac8fc28317398aa431ff6c04209f30673a118260d97713970e8d8d80aa9c3

test:
  secret_key_base: b6e1d0393227d1ee26f98ce6633e3bea6cda92109d2e10e8181add4ae55c88cefb445773c3fa2c13938a6229c700a97fca33f85fa92d9c8fc98e5e29737c9d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
